package com.myspace.brew;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Order implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private int amountOfBottled10;
	private int amountOfBottled12;
	private int amountOfKegged10;
	private int amountOfKegged12;
	private boolean needRestock;

	private java.time.LocalDateTime deliveryTime;

	private boolean readyToDeliver;

	private boolean deliveryRecieved;

	private boolean customerAvalaible;

	private java.lang.String customerName;

	private java.lang.String customerAddress;

	private int numOfCalls;

	private boolean accident;

	private java.lang.Boolean completed;

	private java.lang.String customerNumber;

	private java.lang.String customerEmail;

	public Order() {
	}

	public int getAmountOfBottled10() {
		return this.amountOfBottled10;
	}

	public void setAmountOfBottled10(int amountOfBottled10) {
		this.amountOfBottled10 = amountOfBottled10;
	}

	public int getAmountOfBottled12() {
		return this.amountOfBottled12;
	}

	public void setAmountOfBottled12(int amountOfBottled12) {
		this.amountOfBottled12 = amountOfBottled12;
	}

	public int getAmountOfKegged10() {
		return this.amountOfKegged10;
	}

	public void setAmountOfKegged10(int amountOfKegged10) {
		this.amountOfKegged10 = amountOfKegged10;
	}

	public int getAmountOfKegged12() {
		return this.amountOfKegged12;
	}

	public void setAmountOfKegged12(int amountOfKegged12) {
		this.amountOfKegged12 = amountOfKegged12;
	}

	public boolean isNeedRestock() {
		return this.needRestock;
	}

	public void setNeedRestock(boolean needRestock) {
		this.needRestock = needRestock;
	}

	public java.time.LocalDateTime getDeliveryTime() {
		return this.deliveryTime;
	}

	public void setDeliveryTime(java.time.LocalDateTime deliveryTime) {
		this.deliveryTime = deliveryTime;
	}

	public boolean isReadyToDeliver() {
		return this.readyToDeliver;
	}

	public void setReadyToDeliver(boolean readyToDeliver) {
		this.readyToDeliver = readyToDeliver;
	}

	public boolean isDeliveryRecieved() {
		return this.deliveryRecieved;
	}

	public void setDeliveryRecieved(boolean deliveryRecieved) {
		this.deliveryRecieved = deliveryRecieved;
	}

	public boolean isCustomerAvalaible() {
		return this.customerAvalaible;
	}

	public void setCustomerAvalaible(boolean customerAvalaible) {
		this.customerAvalaible = customerAvalaible;
	}

	public java.lang.String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(java.lang.String customerName) {
		this.customerName = customerName;
	}

	public java.lang.String getCustomerAddress() {
		return this.customerAddress;
	}

	public void setCustomerAddress(java.lang.String customerAddress) {
		this.customerAddress = customerAddress;
	}

	public int getNumOfCalls() {
		return this.numOfCalls;
	}

	public void setNumOfCalls(int numOfCalls) {
		this.numOfCalls = numOfCalls;
	}

	public boolean isAccident() {
		return this.accident;
	}

	public void setAccident(boolean accident) {
		this.accident = accident;
	}

	public java.lang.Boolean getCompleted() {
		return this.completed;
	}

	public void setCompleted(java.lang.Boolean completed) {
		this.completed = completed;
	}

	public java.lang.String getCustomerNumber() {
		return this.customerNumber;
	}

	public void setCustomerNumber(java.lang.String customerNumber) {
		this.customerNumber = customerNumber;
	}

	public java.lang.String getCustomerEmail() {
		return this.customerEmail;
	}

	public void setCustomerEmail(java.lang.String customerEmail) {
		this.customerEmail = customerEmail;
	}

	public Order(int amountOfBottled10, int amountOfBottled12,
			int amountOfKegged10, int amountOfKegged12, boolean needRestock,
			java.time.LocalDateTime deliveryTime, boolean readyToDeliver,
			boolean deliveryRecieved, boolean customerAvalaible,
			java.lang.String customerName, java.lang.String customerAddress,
			int numOfCalls, boolean accident, java.lang.Boolean completed,
			java.lang.String customerNumber, java.lang.String customerEmail) {
		this.amountOfBottled10 = amountOfBottled10;
		this.amountOfBottled12 = amountOfBottled12;
		this.amountOfKegged10 = amountOfKegged10;
		this.amountOfKegged12 = amountOfKegged12;
		this.needRestock = needRestock;
		this.deliveryTime = deliveryTime;
		this.readyToDeliver = readyToDeliver;
		this.deliveryRecieved = deliveryRecieved;
		this.customerAvalaible = customerAvalaible;
		this.customerName = customerName;
		this.customerAddress = customerAddress;
		this.numOfCalls = numOfCalls;
		this.accident = accident;
		this.completed = completed;
		this.customerNumber = customerNumber;
		this.customerEmail = customerEmail;
	}

}