package com.myspace.brew;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RestockRequest implements java.io.Serializable {

	private int amountOfBottled10;
	private int amountOfBottled12;
	private int amountOfKegged10;
	private int amountOfKegged12;

	public RestockRequest() {
	}

	public int getAmountOfBottled10() {
		return this.amountOfBottled10;
	}

	public void setAmountOfBottled10(int amountOfBottled10) {
		this.amountOfBottled10 = amountOfBottled10;
	}

	public int getAmountOfBottled12() {
		return this.amountOfBottled12;
	}

	public void setAmountOfBottled12(int amountOfBottled12) {
		this.amountOfBottled12 = amountOfBottled12;
	}

	public int getAmountOfKegged10() {
		return this.amountOfKegged10;
	}

	public void setAmountOfKegged10(int amountOfKegged10) {
		this.amountOfKegged10 = amountOfKegged10;
	}

	public int getAmountOfKegged12() {
		return this.amountOfKegged12;
	}

	public void setAmountOfKegged12(int amountOfKegged12) {
		this.amountOfKegged12 = amountOfKegged12;
	}

	public RestockRequest(int amountOfBottled10, int amountOfBottled12,
			int amountOfKegged10, int amountOfKegged12) {
		this.amountOfBottled10 = amountOfBottled10;
		this.amountOfBottled12 = amountOfBottled12;
		this.amountOfKegged10 = amountOfKegged10;
		this.amountOfKegged12 = amountOfKegged12;
	}
	public String toString(){
	    return " Please deliver these items into warehouse:\n" +
	    "Bottled 10: "+ this.amountOfBottled10 + "\n" +
	    "Bottled 12: "+ this.amountOfBottled12 + "\n" +
	    "Kegged 10: "+ this.amountOfKegged10 + "\n" +
	    "Kegged 12: "+ this.amountOfKegged12 + "\n";
	    
	}
}